### ISSUE TITLE
Destroy and re-initialize the overflow object.

### ISSUE THREAD

**Issue by dMOTION** [anseki/overflow-android#1] opened 2015-03-08 13:42 UTC
Is it possible to destroy the overflow object (so it's status is resetted and not listening to swipes anylonger) and re-initialize is afterwards?

I'm having troubles with this script in my app; when I switch orientation, the layout is re-calculated (it uses ViewportWidth / -Height as units to calculate the layout) and the plugin is not adapting the new situation.

Destroying the elements behaviour and re-calculating it may solve the problem...

**Comment by anseki** [comment] 2015-03-08 17:05
Hi dmotion
Try [`initSize`](https://github.com/anseki/overflow-android#initsize) method.
Or, if you test about confliction, [`OverflowAndroid.enable`](https://github.com/anseki/overflow-android#user-content-overflowandroidenable) option may help you. This controls sizing object when the window is resized.

**Comment by dMOTION** [comment] 2015-03-08 17:32
![clipboard-1](https://cloud.githubusercontent.com/assets/2298150/6547241/fa3a72c0-c5d2-11e4-92ec-cde48aeb9e1c.png)
Thanks for the quick response!

I tried both methods (even before posting to this page) - but none of them did work...

The scrollable area scrolls out of view when switching from portrait to landscape mode and weird (scroll) artefacts are happening... I think it's caused by my app -which uses a responsive layout, using CSS VW and VH (which doesn't work under Android 4.x - so I wrote a polyfill to enable this)...

I am now altering the hammer.js script - when I've found the solution I'll post it here!

BTW - the script works perfect on Windows Tablets and Windows Phone and Windows Desktop - but gives (in my situation) some troubles when using under Android (4.0).

I tried many scroll / swipe / gesture plugins - but yours works the best and fastest - even on low-end Android 4.x devices (iScroll didn't work at all). It's really great for backword-compatible apps!

UPDATE

I think I've a very special user-case, but I managed to get it working. Android 4.0 doesn't support scrollLeft() and it also doesn't support VW and VH as CSS units. My app uses both...

I discovered that I had to change this.scrollMax.left to it's equivalent of Math.ceil($(window).width()*1.62) -> which is the exact width of the contents in the DIV I want to scroll under Android 4.x...

I also had to remove the Y-axis swipes from hammer.js -> but everything is working now!

**Comment by anseki** [comment] 2015-03-09 07:27
Thank you for your report.
Sorry but, I can't understand the cause of this trouble well...
You said that OverflowAndroid fails to set `this.scrollMax.left` in `initSize`, right?
That is calculated from `this.positionMax.left` and `this.positionMin.left`, and those are calculated from the `view.clientWidth` and the `content.offsetWidth`.
That is, those properties don't work?
I think that it might cause also the other matters too.
How I should fix OverflowAndroid to calculate it?

BTW, I'm glad to your evaluation, because I focused the performance of motion. But I can't get the good way to use CSS Animations yet.
https://github.com/anseki/overflow-android#overflowandroidtransition

**Comment by dMOTION** [comment] 2015-03-09 10:15
I am sure my situation is unique and has nothing to do with your excellent plugin. I will try to upload a video with the situation explained - but it's a rare user-case, due to the use of viewportwidth- and height in Android 4.x I'm afraid...

I've also tried to animate a background using CSS-transitions (it should be faster, 'cause it's more native than Javascript) but on low-end devices it's very slow... So I ended up using a combination of CSS and JS (pure JS also didn't work).

Guess we have to deal with low-end devices as well ;)

**Comment by anseki** [comment] 2015-03-09 15:02
Ok, Thanks! :smiley:
We are always tormented by different platforms... I hope that plugins help about it, even just a little.
Well, I close this issue, ok? Please reopen it, if there is problem.

**Closed as completed by anseki** 2015-03-09 15:02 UTC

**Comment by dMOTION** [comment] 2015-03-09 15:28
Closing the "issue" is okay with me. I've discovered a work-around;

When you rotate a low-end Android device, your sizeInit() is fired at once  (listener at 'resize'). But Android itself needs some time to re-calculate the new interface (in my situation, because I use an  adaptive lay-out system for my app).

So your sizeInit() calculates the previous lay-out, while Android is setting up the new one... the result is that the scroller behaves like it was in the old lay-out and not in the current one.

So I decided to delay the sizeInit() on rotation, for about 1 second (which is enough) and now everything works fine - even on low-end hardware :)

![clipboard-1](https://cloud.githubusercontent.com/assets/2298150/6558087/15f48a8a-c67a-11e4-9c87-9410c407cb9a.png)

**Comment by anseki** [comment] 2015-03-09 15:56
I see, but I expected that situation, and I wrote `initSize` API.
That is, If the size of elements was changed by other than window resizing, this method must be called.
I think better way is that your app calls the `initSize` after the app finishes the layout.

**Comment by dMOTION** [comment] 2015-03-09 20:10
Cool - I can't really check when the lay-out is finished rendering, 'cause this is determined by the speed of the hardware CPU / GPU.

But I added an advanced listener to the resize / rotation-event and for this moment everything is working. You can check the app (debug) here - http://youtu.be/v7oAIoMD268

Please, keep in mind the app is still under developing - I use the plugin for the scrollist in the footer.

**Comment by anseki** [comment] 2015-03-09 23:42
Very cute visual! Nice looking!
Yes, I understand difficulty about different hardware or environment.
And, I'm anxious about "delay time: 1 second" you said.
- Slow machine: The rendering might require more than 1 second.
- Fast machine: The user might be kept waiting until `initSize` is done, even if rendering is finished.

Maybe, is your app using `matchMedia#addListener`?
Or, you said that you wrote the polyfill for responsive layout. That polyfill might be using `matchMedia#addListener`.
The change event of `matchMedia` is fired by result of the layout-calculation. That is done after `window#resize` event, because the layout is calculated from window size. That is, the change event of `matchMedia` is fired after `window#resize` event.
Therefore, `initSize` might have to be called in the change event of `matchMedia`. It's called when the layout is fixed.

``` js
window.matchMedia(mediaQuery).addListener(function() { overflowA.initSize(); });
```

By this way, `initSize` might be called twice. But don't set `false` to `overflowA.enable` to avoid `initSize` called from `window#resize` event, if you support environment that fires `window#resize` event without the change event of `matchMedia`. (i.e. desktop)

**Comment by anseki** [comment] 2015-03-10 00:01
Or, if your app or your polyfill changes the layout in `window#resize` event, check the order of adding those handlers. For example, move the `<script>` tag of OverflowAndroid to the lower.

**Comment by dMOTION** [comment] 2015-03-10 19:43
Thanks for the suggestions - I didn't even know that "window.matchMedia(mediaQuery)" was existing - so I didn't use it (but it's a very usefull technique, thanks again for suggesting it!).

https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

At this moment I call the initSize() without delays, when resizing / rotating the device-screen. And after about one second, I check if things have changed (and call initSize() again when needed).

Fast devices execute the initSize() at once, slow devices don't - but the execute it after one second... sort of progressive enhancement / gracefull degredation :)

I will check out some other things and update it overhere - and once again I want to make clear that the issues are caused by my set-up / particular user-case and not by your excellent plug-in, which is much better than all the alternatives I've tried (and killed).

**Comment by anseki** [comment] 2015-03-11 06:19
Ok, but carefully:
As I said, I think better way is direct-calling that doesn't depend on the time. `initSize` certainly be called after layout is finished, and it's not called repeatedly.
But, if your app isn't able to call `initSize` directly and it uses timer, note that the task might require more than 2 seconds when CPU is doing other tasks. (Even the timer isn't precision always.)
And, I recommend that you don't change the code of OverflowAndroid, because you have to follow it when I update OverflowAndroid.

**Comment by dMOTION** [comment] 2015-03-11 18:30
Yeah, I know it's bad practice to alter the original code :)

But I had to alter many lines of the original plug-in, in order to make it compatible with my app.

I had to remove all Y-Axis references, for instance, because my scroll-element was also scrolling on the Y-Axis - even when that's not necessary (there's no space for the item to scroll vertically - but I was able to do so - so I blocked all the scrolling for the Y-Axis). 

And even good old Internet Explorer 10 (both mobile and desktop - which are sharing the render-engine and code-base) was not doing it right.

But I now have a stable situation; it works perfect, even under Android 4.0, Internet Explorer 10, etc....

Thanks again for writing this plug-in; it's the best and smoothest I've tried, seen and used!
